### PR TITLE
Add Guide

### PR DESCRIPTION
**Pull request by Ceyron**
Adds the Guide written by @wi-re for programming exercise 0.

I changed the images to be hosted on GitHub.

### CODE REVIEW

**Comment by Davidxdydz** [comment]
The guide looks good, but relies on the key input from #7, which might still be subject to change.
A function-local using directive:
```cpp
void Scene1::onDraw(Renderer& renderer){
	using namespace glm; // this is new
    // renderer.drawWireCube(glm::vec3(0), glm::vec3(5), glm::vec3(1));
	renderer.drawWireCube(vec3(0), vec3(5), vec3(1));
}
``` 
or explicit aliases in the class declaration for `Scene`:
```cpp
class Scene1 : public Scene
{
    using vec3 = glm::vec3;
};
```
could be used to make the notation lighter.
This can also be applied to the ImGui namespace in the `onGUI()` function.

**Comment by Ceyron** [comment]
> The guide looks good, but relies on the key input from #7, which might still be subject to change.
Based on that, I think it's best if we remove key trigger from the guide from now such that we can merge as soon as possible. Wdyt @wi-re?

> A function-local using directive:
> 
> ```c++
> void Scene1::onDraw(Renderer& renderer){
> 	using namespace glm; // this is new
>     // renderer.drawWireCube(glm::vec3(0), glm::vec3(5), glm::vec3(1));
> 	renderer.drawWireCube(vec3(0), vec3(5), vec3(1));
> }
> ```
> 
> or explicit aliases in the class declaration for `Scene`:
> 
> ```c++
> class Scene1 : public Scene
> {
>     using vec3 = glm::vec3;
> };
> ```
> 
> could be used to make the notation lighter. This can also be applied to the ImGui namespace in the `onGUI()` function.

In my limited experience with C++, I personally prefer keeping the namespaces. It's probably a good practice.

**Comment by Davidxdydz** [comment]
> In my limited experience with C++, I personally prefer keeping the namespaces. It's probably a good practice
As long as the using directives are not in the header or global, there is no drawback in using them to improve code readability.

**Comment by wi-re** [comment]
The guide should be updated now to have immediate mode and event based input to show both options and some additional section headings for legibility. This should make the commit mergeable without objections?

As a side note, `using namespace` can have very odd behavior and bugs with ADL, e.g., (code from https://bajamircea.github.io/coding/cpp/2017/02/22/noncopyable-adl.html) ```cpp
namespace X {
  struct Y {};
  void some_fn(const Y &) {}
}

int main() {
  X::Y z;
  some_fn(z);
}
```
which will work as ADL sees that the argument z is in a namespace and that within this namespace a function `some_fn` exists. If we now were to use a namespace like std, e.g., `using namespace std` within the function and std had a function of equal name then which one is called? This can be actually be _used_ in some cases with swapping where using namespace std provides a baseline implementation for swapping objects but if the namespace the objects reside in also has a swap function then this function is preferred, e.g., this example: https://godbolt.org/z/4aP7Kv68v

However, this can also lead to other issues where someone would have expected std::swap to get picked (as using namespace std is right above the function), but it is not. Accordingly I am a firm believer in never using namespaces (pun intended) unless there is a good and informed decision being made, except if code has to fit on a slide (which it does not have to here).

**Review by wi-re — APPROVED** [review]

**Pull request merged**
